name: Release

on:
  pull_request:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build --rm -t phantomized .

      - name: Run Docker image
        run: docker run --name phantomized  -e PHANTOM_VERSION=2.1.1 phantomized

      - name: Copy file from Docker container
        run: docker cp phantomized:/app/dockerized-phantomjs.tar.gz ./dockerized-phantomjs.tar.gz

      - name: Remove Docker container
        run: docker rm phantomized

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dockerized-phantomjs
          path: ./dockerized-phantomjs.tar.gz
